### ISSUE TITLE
Polish IBANs are broken in CountryCodesData.java

### ISSUE THREAD

**Issue by olmaga** [barend/java-iban#62]
Hi there I noticed that the Bank Code extraction is broken because the generated info in BANK_CODE_BRANCH_CODE is broken.

According to https://github.com/barend/java-iban/blob/main/src/main/resources/nl/garvelink/iban/IBAN.yml
The bank code is missing and only the branch is added:

I think it needs to be:
```
  name: Poland
    country_code: PL
    length: 28
    flags:
      sepa_country: yes
      in_swift_registry: yes
    embeds:
      bank_code:
        position: 4
        length: 8
```
